admission_form/urls.py
from django.contrib import admin
from django.urls import include, path
from pentagon import views

urlpatterns = [
    path('', views.home, name='home'),
    path('new_admission/', include('pentagon.urls')),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
]

pentagon/urls.py
from django.urls import path

from . import views

app_name = 'pentagon'
urlpatterns = [
    path('', views.guidelines, name='guidelines'),
    path('guidelines_verify/', views.guidelines_verify, name='guidelines_verify'),
    path('admission_form/', views.admission_form, name='admission_form'),
    path('acknowledgement/', views.acknowledgement, name='acknowledgement'),
    path('already_exists/', views.already_exists, name='already_exists'),
]

pentagon/models.py
from cProfile import label
from django.db import models

grade_choices = [
    ('Nursery', 'Nur'),
    ('LKG', 'LKG'),
    ('UKG', 'UKG'),
    ('I', 'I'),
    ('II', 'II'),
    ('III', 'III'),
    ('IV', 'IV'),
    ('V', 'V'),
    ('VI', 'VI'),
    ('VII', 'VII'),
    ('VIII', 'VIII'),
    ('IX', 'IX'),
    ('X', 'X'),
    ('XI', 'XI'),
]

gender_choices = [
    ('Male', 'Male'),
    ('Female', 'Female'),
]

class Student(models.Model):
    # Student Details
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    dob = models.DateField()
    nationality = models.CharField(max_length=100)
    mother_tongue = models.CharField(max_length=100)
    grade = models.CharField(choices=grade_choices ,max_length=100)
    gender = models.CharField(choices=gender_choices ,max_length=100)
    religion = models.CharField(max_length=100)
    place_of_birth = models.CharField(max_length=100)
    # Parent Details
    father_name = models.CharField(max_length=100)
    mother_name = models.CharField(max_length=100)
    father_qualification = models.CharField(max_length=100)
    mother_qualification = models.CharField(max_length=100)
    father_occupation = models.CharField(max_length=100)
    mother_occupation = models.CharField(max_length=100)
    father_designation = models.CharField(max_length=100)
    mother_designation = models.CharField(max_length=100)
    father_organisation = models.CharField(max_length=150)
    mother_organisation = models.CharField(max_length=150)
    father_mobile = models.CharField(max_length=10)
    mother_mobile = models.CharField(max_length=10)
    father_email = models.EmailField(max_length=100)
    mother_email = models.EmailField(max_length=100)
    # Residential Details
    address = models.TextField()
    pincode = models.CharField(max_length=6)

    def __str__(self):
        return self.first_name

        

pentagon/forms.py
from django.forms import ModelForm, DateInput, Textarea, NumberInput
from .models import Student
from captcha.fields import CaptchaField

class AdmissionForm(ModelForm):
    captcha = CaptchaField()
    
    class Meta:
        model = Student
        fields = "__all__"
        labels = {
            "first_name":"First Name", # Student Details
            "last_name":"Last Name",
            "dob":"Date of Birth",
            "nationality":"Nationality",
            "mother_tongue":"Mother Tongue",
            "grade":"Grade",
            "gender":"Gender",
            "religion":"Religion",
            "place_of_birth":"Place of Birth",
            "father_name":"Father's Name", # Parent Details
            "mother_name":"Mother's Name",
            "father_qualification":"Father's Qualification",
            "mother_qualification":"Mother's Qualification",
            "father_occupation":"Father's Occupation",
            "mother_occupation":"Mother's Occupation",
            "father_designation":"Father's Designation",
            "mother_designation":"Mother's Designation",
            "father_organisation":"Father's Organisation Name & Address",
            "mother_organisation":"Mother's Organisation Name & Address",
            "father_mobile":"Father's Mobile Number",
            "mother_mobile":"Mother's Mobile Number",
            "father_email":"Father's Email ID",
            "mother_email":"Mother's Email ID",
            "address":"Residential Address", # Residential Details
            "pincode":"Pincode"
        }
        widgets = {
        'dob': DateInput(format=('%d/%m/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
        'address': Textarea(attrs={'cols': 20, 'rows': 3}),
        'father_mobile':NumberInput(),
        'mother_mobile':NumberInput(),
        'pincode':NumberInput(),
        }

pentagon/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import AdmissionForm
from .models import Student

guidelines_verified = False
form_submitted = False

def home(request):
    return render(request, 'pentagon/home.html')

def guidelines(request):
    return render(request, 'pentagon/guidelines.html')

def guidelines_verify(request):
    global guidelines_verified
    try:
        if request.POST['agree']:
            guidelines_verified = True
            return redirect('pentagon:admission_form')
    except:
        guidelines_verified = False
        return render(request, 'pentagon/guidelines.html', {
            'error_message':'Please Select "I Agree" to continue. '
        })

def admission_form(request):
    global guidelines_verified
    global form_submitted

    if guidelines_verified:
        context = {}

        form = AdmissionForm(request.POST or None, request.FILES or None)

        if form.is_valid():
            form_submitted = True
            name = request.POST['first_name']
            father = request.POST['father_name']
            if Student.objects.filter(first_name=name, father_name=father): # If student name and father name already exists then the form is not saved once again.
                return redirect('pentagon:already_exists')
            else:
                form.save()
                return redirect('pentagon:acknowledgement')

        context['form'] = form
        return render(request, 'pentagon/admission_form.html', context)
    else:
        return redirect('pentagon:guidelines')

def acknowledgement(request):
    global form_submitted
    if form_submitted:
        return render(request, 'pentagon/acknowledgement.html')
    else:
        return redirect('pentagon:admission_form')

def already_exists(request):
    global form_submitted
    if form_submitted:
        return render(request, 'pentagon/already_exists.html')
    else:
        return redirect('pentagon:admission_form')

pentagon/templates/pentagon/acknowledgement.html
{% extends "pentagon/base.html" %}

{% block title %} Submitted {% endblock title %}

{% block content %}
  <h2 class="text-success text-center"> Successfully Submitted !</h2>
{% endblock content %}

pentagon/templates/pentagon/admission_form.html
{% extends "pentagon/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Admission Form {% endblock title %}

{% block content %}
<h1 class = "text-primary text-center"> Admission Registration Form </h1>
<hr>
<br>
<!-- {{ form.first_name|as_crispy_field }} -->
<form method="post">
{% csrf_token %}
<div class="card bg-light">
   <div class="card-body">
     <form>
       <fieldset>
         <legend class="text-white bg-primary text-center"> Student Details </legend>
         <div class="row">
           <div class="col-md-6">
            {{ form.first_name|as_crispy_field }}
           </div>
           <div class="col-md-6">
            {{ form.last_name|as_crispy_field }}
           </div>
         </div>
         <br>
         <div class="row">
           <div class="col-md-6">
            {{ form.dob|as_crispy_field }}
           </div>
           <div class="col-md-6">
            {{ form.nationality|as_crispy_field }}
           </div>
         </div>
         <br>
         <div class="row">
           <div class="col-md-6">
            {{ form.mother_tongue|as_crispy_field }}
           </div>
           <div class="col-md-6">
            {{ form.religion|as_crispy_field }}
           </div>
         </div>
         <br>
         <div class="row">
           <div class="col-md-6">
            {{ form.grade|as_crispy_field }}
           </div>
           <div class="col-md-6">
            {{ form.gender|as_crispy_field }}
           </div>
           <div class="col-md-6">
            {{ form.place_of_birth|as_crispy_field }}
           </div>
         </div>
       </fieldset>
       <br>
       <fieldset>
         <legend class="text-white bg-primary text-center"> Parent Details </legend>
         <div class="row">
           <div class="col-md-6">
            {{ form.father_name|as_crispy_field }}
           </div>
           <div class="col-md-6">
            {{ form.mother_name|as_crispy_field }}
           </div>
         </div>
         <br>
         <div class="row">
           <div class="col-md-6">
            {{ form.father_qualification|as_crispy_field }}
           </div>
           <div class="col-md-6">
            {{ form.mother_qualification|as_crispy_field }}
           </div>
         </div>
         <br>
         <div class="row">
           <div class="col-md-6">
            {{ form.father_occupation|as_crispy_field }}
           </div>
           <div class="col-md-6">
            {{ form.mother_occupation|as_crispy_field }}
           </div>
         </div>
         <br>
         <div class="row">
           <div class="col-md-6">
            {{ form.father_designation|as_crispy_field }}
           </div>
           <div class="col-md-6">
            {{ form.mother_designation|as_crispy_field }}
           </div>
         </div>
         <br>
         <div class="row">
           <div class="col-md-6">
            {{ form.father_organisation|as_crispy_field }}
           </div>
           <div class="col-md-6">
            {{ form.mother_organisation|as_crispy_field }}
           </div>
         </div>
         <br>
         <div class="row">
           <div class="col-md-6">
            {{ form.father_mobile|as_crispy_field }}
           </div>
           <div class="col-md-6">
            {{ form.mother_mobile|as_crispy_field }}
           </div>
         </div>
         <div class="row">
           <div class="col-md-6">
            {{ form.father_email|as_crispy_field }}
           </div>
           <div class="col-md-6">
            {{ form.mother_email|as_crispy_field }} 
           </div>
         </div>
         <br>
 
       </fieldset>
 
       <fieldset>
         <legend class="text-white bg-primary text-center">Residential Details</legend>
         <div class="row">
           <div class="col-md-6">
            {{ form.address|as_crispy_field }}
            </div>
           <div class="col-md-6">
            {{ form.pincode|as_crispy_field }}
           </div>
         </div>
       </fieldset>
     <br>
     <p class="text-dark"> Captcha </p>
     {{form.captcha}} 
     <br><br>
   <button type="submit" class="btn btn-outline-primary" style="width: 20rem">Submit</button>
</div>
</form>
{% endblock content %}

pentagon/templates/pentagon/admission_form_old.html
{% extends "pentagon/base.html" %}

{% block title %} Admission Form {% endblock title %}

{% block content %}
  <style>
    .required:after {
      content:" *";
      color: red;
    }
  </style>

  <h1 class = "text-primary text-center"> Admission Registration Form </h1>
  <hr>
  <br>
  <div class="card">
  <div class="card-body">
    <form>
      <fieldset>
        <legend class="text-bg-primary text-center"> Student Details </legend>
        <div class="row">
          <div class="col-md-6">
          <label for="FirstName" class="form-label required">Student First Name</label>
          <input type="text" class="form-control" id="FirstName" placeholder="First Name" required>
          </div>
          <div class="col-md-6">
            <label for="LastName" class="form-label required">Student Last Name</label>
            <input type="text" class="form-control" id="LastName" placeholder="Last Name" required>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-6">
          <label for="DOB" class="form-label required">Student Date of Birth</label>
          <input type="date" class="form-control" id="DOB" required>
          </div>
          <div class="col-md-6">
            <label for="Nationality" class="form-label required">Nationality</label>
            <input type="text" class="form-control" id="Nationality" placeholder="Nationality" required>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-6">
          <label for="MotherTongue" class="form-label required">Mother Tongue</label>
          <input type="text" class="form-control" id="MotherTongue" placeholder="Mother Tongue" required>
          </div>
          <div class="col-md-6">
            <label for="Religion" class="form-label required">Religion</label>
            <input type="text" class="form-control" id="Religion" placeholder="Religion" required>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-6">
            <label for="grade" class="form-label required">Student Grade</label>
            <select class="form-select" id="grade" required>
              <option selected>Select Grade</option>
              <option value="Nursery">Nursery</option>
              <option value="LKG">LKG</option>
              <option value="UKG">UKG</option>
              <option value="1">I</option>
              <option value="2">II</option>
              <option value="3">III</option>
              <option value="4">IV</option>
              <option value="5">V</option>
              <option value="6">VI</option>
              <option value="7">VII</option>
              <option value="8">VIII</option>
              <option value="9">IX</option>
              <option value="10">X</option>
              <option value="11">XI</option>
            </select>
          </div>
          <div class="col-md-6">
            <label for="gender" class="form-label required">Student Gender</label>
            <select class="form-select" id="gender" required>
              <option selected>Select Gender</option>
              <option value="Male">Male</option>
              <option value="Female">Female</option>
            </select>
          </div>
        </div>
      </fieldset>
      <br>
      <fieldset>
        <legend class="text-bg-primary text-center"> Parent Details </legend>
        <div class="row">
          <div class="col-md-6">
          <label for="FatherName" class="form-label required">Father Name</label>
          <input type="text" class="form-control" id="FatherName" placeholder="Father Name" required>
          </div>
          <div class="col-md-6">
            <label for="MotherName" class="form-label required">Mother Name</label>
            <input type="text" class="form-control" id="MotherName" placeholder="Mother Name" required>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-6">
          <label for="FatherQual" class="form-label required">Father's Qualification</label>
          <input type="text" class="form-control" id="FatherQual" placeholder="Qualification" required>
          </div>
          <div class="col-md-6">
            <label for="MotherQual" class="form-label required">Mother's Qualification</label>
            <input type="text" class="form-control" id="MotherQual" placeholder="Qualification" required>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-6">
          <label for="FatherOccu" class="form-label required">Father's Occupation</label>
          <input type="text" class="form-control" id="FatherOccu" placeholder="Occupation" required>
          </div>
          <div class="col-md-6">
            <label for="MotherOccu" class="form-label required">Mother's Occupation</label>
            <input type="text" class="form-control" id="MotherOccu" placeholder="Occupation" required>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-6">
          <label for="FatherDesig" class="form-label required">Father's Designation</label>
          <input type="text" class="form-control" id="FatherDesig" placeholder="Designation" required>
          </div>
          <div class="col-md-6">
            <label for="MotherDesig" class="form-label required">Mother's Designation</label>
            <input type="text" class="form-control" id="MotherDesig" placeholder="Designation" required>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-6">
          <label for="FatherOrg" class="form-label required">Father's Organisation's Name and Address </label>
          <input type="text" class="form-control" id="FatherOrg" placeholder="Organisation" required>
          </div>
          <div class="col-md-6">
            <label for="MotherOrg" class="form-label required">Mother's Organisation's Name and Address</label>
            <input type="text" class="form-control" id="MotherOrg" placeholder="Organisation" required>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-6">
          <label for="FatherMobile" class="form-label required">Father's Mobile Number</label>
          <input type="tel" pattern="[0-9]{10}" class="form-control" id="FatherMobile" placeholder="Mobile Number" maxlength="10" required>
          </div>
          <div class="col-md-6">
            <label for="MotherMobile" class="form-label required">Mother's Mobile Number</label>
            <input type="tel" pattern="[0-9]{10}" class="form-control" id="MotherMobile" placeholder="Mobile Number" maxlength="10" required>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-6">
          <label for="Res1" class="form-label">Residential Number 1</label>
          <input type="tel" pattern="[0-9]{10}" class="form-control" id="Res1" placeholder="Residential Number" maxlength="10">
          </div>
          <div class="col-md-6">
            <label for="Res2" class="form-label">Residential Number 2</label>
            <input type="tel" pattern="[0-9]{10}" class="form-control" id="Res2" placeholder="Residential Number" maxlength="10">
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-6">
          <label for="FatherEmail" class="form-label required">Father's Email ID </label>
          <input type="email" class="form-control" id="FatherEmail" placeholder="Email ID" required>
          </div>
          <div class="col-md-6">
            <label for="MotherEmail" class="form-label required">Mother's Email ID</label>
            <input type="email" class="form-control" id="MotherEmail" placeholder="Email ID" required> 
          </div>
        </div>
        <br>
        </div>
      </fieldset>

      <fieldset>
        <legend class="text-bg-primary text-center">Residential Details</legend>
        <div class="row">
          <div class="col-md-6">
            <label for="Address" class="form-label required">Address</label>
            <input type="text" class="form-control" id="Address" placeholder="Address" required>
          </div>
          <div class="col-md-6">
            <label for="Pincode" class="form-label required">Pincode</label>
            <input type="text" class="form-control" id="Pincode" placeholder="Pincode" required>
          </div>
        </div>
      </fieldset>
    <br> 
  <button type="submit" class="btn btn-outline-primary" style="width: 20rem">Submit</button>
  </div>
</form>
</div>
{% endblock content %}

pentagon/templates/pentagon/already_exists.html
{% extends "pentagon/base.html" %}

{% block title %} Already Exists {% endblock title %}

{% block content %}
  <h2 class="text-danger text-center"> Your form already exists ! </h2>
{% endblock content %}

pentagon/templates/pentagon/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
  <body>
    {% block content %}{% endblock content %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </body>
</html>

pentagon/templates/pentagon/base_old.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    {% block content %}{% endblock content %}
  </body>
</html>

pentagon/templates/pentagon/guidelines.html
{% extends "pentagon/base.html" %}

{% block title %} Guidelines {% endblock title %}

{% block content %}
  <h2 class="text-center text-primary"> Guidelines For Online Admission </h2>
  <h4 class="text-center text-secondary text-opacity-75"> 2022-23 </h4>
  <hr>
  <br>

  <div class="alert  alert-primary d-flex align-items-center" role="alert">
    Kindly read all the instructions carefully before you click on Proceed at the bottom of this page.
  </div>
  <br>
  <div class="card text-white bg-primary mb-3" style="width: 100%">
    <div class="card-header text-center fw-semibold">Guidelines</div>
    <div class="card-body">
    <ol class="list-group list-group-numbered">
      <li class="list-group-item text-white bg-primary"> It is mandatory to have a valid personal email if communication. </li>
      <li class="list-group-item text-white bg-primary"> Kindly fill in the particulars of the child (i.e name, parent's names and date of birth) correctly. </li>
      <li class="list-group-item text-white bg-primary"> The date of birth filled in the form must tally with the birth certificate of the child. </li>
      <li class="list-group-item text-white bg-primary"> The Management of the school reserves all rights of admission or rejection and it is not bound to give reasons for the admission or rejection of any particular candidate. </li>
      <li class="list-group-item text-white bg-primary"> Incomplete registration forms or those with incorrect information will automatically stand rejected. </li>
    </ol>
    </div>
    </div>
    <br>
    <form class="bg-light" action="{% url 'pentagon:guidelines_verify' %}" method="post">
    {% csrf_token %}
    <fieldset>
    &nbsp; I hereby agree that I have read all the Guidelines. I also acknowledge to be contacted by the school management for any further details.
    <div class="form-check">
        &nbsp;
        <input class="form-check-input" type="checkbox" name="agree" value="agreed" id="agreecheckbox">
        <label class="form-check-label text-success" for="agreecheckbox">
            I Agree
        </label>
    </div>
    <br>
    {% if error_message %}<div class="alert alert-warning">{{ error_message }}</div>{% endif %}
    <button type="submit" class="btn btn-outline-success">Next</button> 
    </fieldset>
    </form>

{% endblock content %}

pentagon/templates/pentagon/home.html
{% extends "pentagon/base.html" %}

{% block title %} Home {% endblock title %}

{% block content %}
  <h2 class="text-dark"> Home Page </h2>
  <br>
  <a class="btn btn-outline-primary" href={% url 'pentagon:guidelines' %} role="button">New Admission</a>
{% endblock content %}